general:
  project_name: 'BarcodeSegmentation'
  experiment_name: 'first_run'
  max_steps: 5000
  dotenv_path: '.env'

hardware:
  accelerator: 'gpu'
  precision: 32
  devices: [0, 1]

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 1e-4
  weight_decay: 1e-5

scheduler: 'detector.utils.schedulers.CosineAnnealingWarmup'
scheduler_kwargs:
  min_lr: 1e-6
  warmup_steps: 500
  decay_steps: 4500

callbacks:
  monitor_metric: 'val_TopKNormalizedOverlap@50'
  monitor_mode: 'max'
  early_stopping_patience: 10
  progress_bar_refresh_rate: 10

model:
  video_pos_encoder: 'detector.models.blocks.transformer_blocks.PositionalEncoding'
  video_pos_encoder_kwargs:
    dim: 768
    dropout: 0.1

losses:
  -
    name: "SegLoss"
    loss_weight: 2
    loss_fn: "src.models.losses.classification.WeightedCrossEntropyLoss"
    loss_kwargs:
      reduction: "mean"


base_data_settings:
  img_train: "data/films_features/video"
  annotation_train: "data/films_features/audio"
  batch_size: 6
  max_len:
  num_workers: 10
